### ISSUE TITLE
Warning is python dependencies are not installed

### ISSUE THREAD

**Issue by saberraz** [saberraz/qgis-ecmwf-catalogue-plugin#5]
Should ask user to install ECMWF python package first:
https://software.ecmwf.int/wiki/display/WEBAPI/Accessing+ECMWF+data+servers+in+batch#AccessingECMWFdataserversinbatch-python

**Comment by Kanter666** [comment]
This is the same case as Crayfish dependencies. QGIS has built in dependency checker that won't allow to install/run plugin without required dependencies. It also writes which module is missing - instructions how to install important dependencies in the description should be enough.

**Comment by Kanter666** [comment]
Added instructions and merged to master.
